### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by siteswapjuggler** [crpalmer/gcode2msf#1]
I didn't found any contact information on your profile page and would like to exchange about this program you made. Chroma seems way out of date and I think of doing some kind of gcode post processing tool for my Palette 2S Pro but didn't found any documentation about the slicing file format. Seems you get further so I hoped we can share informations.

Sincerely

**Comment by crpalmer** [comment]
Slicing produces gcode which is well documented, or did you mean the palette file format?  If so, the palette 2 uses a different file format from the palette 1 which is what this software is designed to produce.  Since I don't own a palette 2, I haven't looked into that file format at all so I don't know anything useful there.

**Comment by siteswapjuggler** [comment]
Thanks for you answer, I will continue to search clues about what to do next with this Palette. I took time those last 3 days and will have enough material to produce the file documentation I was searching in the first place.

Have a nice day and an Happy New Year
